// Home page text. index.html carries the English inline; tests keep the two in sync.

export const STRINGS = {
  en: {
    'name.first': 'DEYAN',
    'name.last': 'TODOROV',
    'nav.epigenesis': 'Epigenesis',
    'nav.research': 'Misul',
    'nav.projects': 'Independent',
    'nav.contact': 'Contact',
    'about.statement': 'I believe in doing a job 100% or not doing it at all.',
    'epigenesis.lead': 'DNA is a recipe, so I wrote a compiler for it.',
    'epigenesis.vision': 'In biology a brain gets built from the instructions in DNA, and I wanted to try the same thing in software. You give Epigenesis a DNA sequence and tell it how to read it. It gives back a module that describes how something develops, and it seals that module so anyone can run it again and get the same result.',
    'epigenesis.desc': 'It reads FASTA, GenBank and GFF3 files. So far it runs two published models of how neural cells pick their fate, grows small networks from a single starting cell, and turns real mutations into proteins. Two of my own predictors failed their tests and I kept them in the repo anyway. Version 1.5 is on GitHub.',
    'research.intro': 'Misul is the AI research lab I started in Sofia. We build models from how the brain works.',
    'interlace.brief': 'A single architecture that handles language and step-by-step computation.',
    'monodratic.brief': 'Sparse attention that only reads the tokens it needs.',
    'laplace.brief': 'An inference engine for Apple Silicon that runs every model through one compiler.',
    'projects.heading': 'Independent',
    'projects.phonecode': 'A coding agent that runs on your Android phone.',
    'projects.optisys': 'Keeps a Windows PC responsive in the background.',
    'projects.dzipobel': 'Literature and grammar notes for the Bulgarian matura.',
    'projects.schoolmap': 'A map tool I made for geography lessons.',
    'opensource.heading': 'Open Source',
    'moltenvk.desc': 'I contribute to Khronos MoltenVK, the Vulkan driver for Apple platforms. Four of my patches are merged. Vulkan ray tracing on macOS, mesh shaders and a few fixes are still in review.',
    'moltenvk.review': 'In review',
    'moltenvk.merged': 'Merged',
  },
  bg: {
    'name.first': 'ДЕЯН',
    'name.last': 'ТОДОРОВ',
    'nav.epigenesis': 'Epigenesis',
    'nav.research': 'Misul',
    'nav.projects': 'Самостоятелни',
    'nav.contact': 'Контакт',
    'about.statement': 'Вярвам в това да свърша работата на 100% или да не я правя изобщо.',
    'epigenesis.lead': 'ДНК е рецепта, затова написах компилатор за нея.',
    'epigenesis.vision': 'В биологията мозъкът се строи по инструкциите в ДНК и исках да пробвам същото в софтуер. Даваш на Epigenesis ДНК последователност и му казваш как да я чете. То връща модул, който описва как нещо се развива, и го запечатва, така че всеки да може да го пусне отново и да получи същия резултат.',
    'epigenesis.desc': 'Чете файлове във формат FASTA, GenBank и GFF3. Засега изпълнява два публикувани модела за това как невронните клетки избират съдбата си, отглежда малки мрежи от една начална клетка и превръща истински мутации в протеини. Два от моите предиктори се провалиха на тестовете си и въпреки това ги оставих в хранилището. Версия 1.5 е в GitHub.',
    'research.intro': 'Misul е лабораторията за изкуствен интелект, която основах в София. Строим модели по начина, по който работи мозъкът.',
    'interlace.brief': 'Една архитектура, която се справя и с език, и с изчисления стъпка по стъпка.',
    'monodratic.brief': 'Разредено внимание, което чете само нужните токени.',
    'laplace.brief': 'Инференс енджин за Apple Silicon, който пуска всеки модел през един компилатор.',
    'projects.heading': 'Самостоятелни',
    'projects.phonecode': 'Агент за програмиране, който работи на телефона ти с Android.',
    'projects.optisys': 'Държи компютъра с Windows бърз на заден план.',
    'projects.dzipobel': 'Записки по литература и граматика за матурата по БЕЛ.',
    'projects.schoolmap': 'Карта, която направих за часовете по география.',
    'opensource.heading': 'Отворен код',
    'moltenvk.desc': 'Допринасям за Khronos MoltenVK, драйвера за Vulkan върху платформите на Apple. Четири мои пача са приети. Vulkan ray tracing за macOS, mesh shaders и няколко поправки още са в преглед.',
    'moltenvk.review': 'В преглед',
    'moltenvk.merged': 'Приети',
  },
};
